name: build nodejs v16 withssl

on: 
  workflow_dispatch:
    inputs:
      tag_date:
        description: 'tag date'     
        required: true

env:
  VERSION: 22.13.0
  ANDROID_NDK_VERSION: r27

jobs:
  build_android_arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        shell: bash
        run: npm install
        
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          add-to-path: false
          
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          bash ./android-static.sh ${{env.VERSION}} arm64 1
      - name: Rename
        run: |
          mv ~/puerts-node/nodejs ~/puerts-node/nodejs_22
      - uses: actions/upload-artifact@v4
        with:
          name: nodejs_bin
          path: ~/puerts-node/**/*
        
  build_android_armv7:
    runs-on: ubuntu-22.04
    steps:
      - name: Install gcc-multilib g++-multilib
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib
      - uses: actions/checkout@v4
      - name: npm install
        shell: bash
        run: npm install
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          add-to-path: false
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          bash ./android-static.sh ${{env.VERSION}} arm 1
      - name: Rename
        run: |
          mv ~/puerts-node/nodejs ~/puerts-node/nodejs_22
      - uses: actions/upload-artifact@v4
        with:
          name: nodejs_bin
          path: ~/puerts-node/**/*
