name: build nodejs v16 withssl

on: 
  workflow_dispatch:
    inputs:
      tag_date:
        description: 'tag date'     
        required: true

env:
  VERSION: 22.13.0
  ANDROID_NDK_VERSION: r24

jobs:
  build_android_arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        shell: bash
        run: npm install
        
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          add-to-path: false
          
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          bash ./android-static.sh ${{env.VERSION}} arm64 1
      - name: Rename
        run: |
          mv ~/puerts-node/nodejs ~/puerts-node/nodejs_22
      - uses: actions/upload-artifact@v4
        with:
          name: nodejs_bin
          path: ~/puerts-node/**/*
        
  build_android_armv7:
    runs-on: ubuntu-22.04
    steps:
      - name: Install gcc-multilib g++-multilib
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib
      - uses: actions/checkout@v4
      - name: npm install
        shell: bash
        run: npm install
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          add-to-path: false
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          bash ./android-static.sh ${{env.VERSION}} arm 1
      - name: Rename
        run: |
          mv ~/puerts-node/nodejs ~/puerts-node/nodejs_22
      - uses: actions/upload-artifact@v4
        with:
          name: nodejs_bin
          path: ~/puerts-node/**/*
        
  publish:
    runs-on: ubuntu-22.04
    needs: [build_android_arm64,build_android_armv7]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nodejs_bin
          path: nodejs_bin/
          
      - name: Create Release Asset
        run: |
          cd nodejs_bin/ && tar cvfz ../nodejs_bin_${{env.VERSION}}.tgz nodejs_22 && cd -
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: NodeJS_${{env.VERSION}}_ssl_${{ github.event.inputs.tag_date }}
          release_name: NodeJS_${{env.VERSION}}(with ssl)_${{ github.event.inputs.tag_date }}
          draft: false
          prerelease: false
          
      - name: Upload nodejs_bin
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nodejs_bin_${{env.VERSION}}.tgz
          asset_name: nodejs_bin_${{env.VERSION}}.tgz
          asset_content_type: application/tgz
          
